/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandDnaRouteImport } from './routes/brand-dna'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminExamplesRouteImport } from './routes/admin.examples'
import { Route as AdminGenerationsRouteImport } from './routes/admin.generations'
import { Route as AdminKpiRouteImport } from './routes/admin.kpi'
import { Route as AdminPlatformTipsRouteImport } from './routes/admin.platform-tips'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDnaRoute = BrandDnaRouteImport.update({
  id: '/brand-dna',
  path: '/brand-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamplesRoute = AdminExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerationsRoute = AdminGenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpiRoute = AdminKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformTipsRoute = AdminPlatformTipsRouteImport.update({
  id: '/platform-tips',
  path: '/platform-tips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-dna': typeof BrandDnaRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/admin/platform-tips': typeof AdminPlatformTipsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-dna': typeof BrandDnaRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/admin/platform-tips': typeof AdminPlatformTipsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-dna': typeof BrandDnaRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/admin/platform-tips': typeof AdminPlatformTipsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brand-dna'
    | '/create'
    | '/dashboard'
    | '/examples'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/content'
    | '/admin/events'
    | '/admin/examples'
    | '/admin/generations'
    | '/admin/kpi'
    | '/admin/platform-tips'
    | '/admin/quotes'
    | '/admin/security'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-dna'
    | '/create'
    | '/dashboard'
    | '/examples'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/content'
    | '/admin/events'
    | '/admin/examples'
    | '/admin/generations'
    | '/admin/kpi'
    | '/admin/platform-tips'
    | '/admin/quotes'
    | '/admin/security'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brand-dna'
    | '/create'
    | '/dashboard'
    | '/examples'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/sitemap.xml'
    | '/verify-email'
    | '/admin/content'
    | '/admin/events'
    | '/admin/examples'
    | '/admin/generations'
    | '/admin/kpi'
    | '/admin/platform-tips'
    | '/admin/quotes'
    | '/admin/security'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrandDnaRoute: typeof BrandDnaRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-dna': {
      id: '/brand-dna'
      path: '/brand-dna'
      fullPath: '/brand-dna'
      preLoaderRoute: typeof BrandDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examples': {
      id: '/admin/examples'
      path: '/examples'
      fullPath: '/admin/examples'
      preLoaderRoute: typeof AdminExamplesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generations': {
      id: '/admin/generations'
      path: '/generations'
      fullPath: '/admin/generations'
      preLoaderRoute: typeof AdminGenerationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpi': {
      id: '/admin/kpi'
      path: '/kpi'
      fullPath: '/admin/kpi'
      preLoaderRoute: typeof AdminKpiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform-tips': {
      id: '/admin/platform-tips'
      path: '/platform-tips'
      fullPath: '/admin/platform-tips'
      preLoaderRoute: typeof AdminPlatformTipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExamplesRoute: typeof AdminExamplesRoute
  AdminGenerationsRoute: typeof AdminGenerationsRoute
  AdminKpiRoute: typeof AdminKpiRoute
  AdminPlatformTipsRoute: typeof AdminPlatformTipsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExamplesRoute: AdminExamplesRoute,
  AdminGenerationsRoute: AdminGenerationsRoute,
  AdminKpiRoute: AdminKpiRoute,
  AdminPlatformTipsRoute: AdminPlatformTipsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrandDnaRoute: BrandDnaRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
